theme: jekyll-theme-minimal
title: Patrick Cadenas
logo: /assets/img/patrick_ux_jr.png
description: Soy un diseñador UX Jr orientado a la creación y mejora de 
productos digitales, me centro en la búsqueda de soluciones que brinden 
coherencia, simplicidad y experiencias agradables.

show_downloads: false
google_analytics:
