theme: jekyll-theme-minimal
logo: /assets/img/patrick_ux_jr.png
title: "Patrick A. Cadenas 2"
description: "Soy un diseñador UX apasionado en la cracion y mejora de productos digitales, me centro en la busqueda de 
soluciones que brinden coherencia, simplicidad y experiencias agradables."
show_downloads: false
google_analytics:

