theme: jekyll-theme-minimal
title: Patrick Cadenas
logo: /assets/img/patrick_ux_jr.png
description: Soy un diseñador UX Jr orientado a la creación y mejora de 
productos digitales, me centro en la búsqueda de soluciones que brinden 
coherencia, simplicidad y experiencias agradables.
<br><br>
He trabajado en proyectos Webs como Móviles, colaboro bien en equipo y 
soy solvente y emprendedor al momento de adoptar responsabilidades, 
trabajo orientado a resultados.
show_downloads: false
google_analytics:
